// Guida comandi per ogni sezione dell'app.
export const GUIDES = {
  today: {
    titolo: 'Guida · Today',
    icona: '☀️',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['A cosa serve', 'Le viste dicono cosa esiste, Progress a che punto è, Today cosa tocca oggi.'],
      ['Il rito', 'La mattina scegli le task, durante il giorno le spunti, la sera guardi cosa hai fatto.'],
      ['Aggiungere', 'Scrivi nella riga in fondo e premi Invio: resta il cursore, così ne aggiungi tante di fila.'],
      ['Modificare', 'Tocca il testo di una task per correggerlo. Invio ed Esc fanno la stessa cosa: escono dalla riga SALVANDO. Vale in tutte le sezioni — uscire da una riga non butta mai via quello che hai scritto.'],
      ['Completare', 'Tocca il quadratino: la riga diventa grigia e barrata. Ritoccalo per annullare.'],
      ['Riordinare', 'Trascina la maniglia ⠿. Con “fatte in fondo” raggruppi le completate.'],
      ['Rimandate', 'Le task non completate passano da sole al giorno dopo. Il badge ↻3 segnala quelle rimandate troppe volte.'],
      ['Ricorrenti', 'Le task ricorrenti (badge ↻) non vengono mai rimandate: se salti un giorno, domani arriva l’istanza nuova.'],
      ['Da una nota', 'Con /oggi (o Ctrl+⇧+T) una riga si SPOSTA qui: esce dalla nota, così la stessa cosa non ti risulta da fare in due posti. Finisce nel cestino della vista, recuperabile 7 giorni, e Ctrl+Z annulla.'],
      ['Origine', 'Il chip ⚡ ricorda da quale nota arriva la task e la riapre con un tocco.'],
      ['Serie', 'Il contatore 🔥 conta i giorni con almeno una task chiusa. I giorni senza task pianificate non la spezzano, e c’è una giornata di grazia al mese.'],
      ['Proposte', 'Le righe con scadenza oggi o già scaduta, prese dalle visioni non archiviate. Con ＋ si spostano qui, come per /oggi.'],
      ['Regole ricorrenti', 'Il pulsante ↻ in alto apre il pannello: ogni giorno, giorni della settimana, giorni del mese o ogni N giorni, con anteprima delle prossime occorrenze.'],
      ['Sera', 'Dopo le 18 (o appena chiudi qualcosa) compare “Come è andata oggi?”: una vittoria e un umore. Chiudere la giornata la archivia nello storico.'],
      ['Settimana', 'In fondo, “La tua settimana” raccoglie le task chiuse, il giorno migliore e le vittorie annotate.'],
      ['Statistiche', 'Nel menu ☰ → Statistiche, scheda Today: serie, ora tipica di chiusura, tenuta delle ricorrenti e un anno di giornate.'],
    ],
  },
  pipe: {
    titolo: 'Guida · Pipe',
    icona: '🌱',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['Visioni', 'Contenitori tinti col loro colore. Racchiudono le viste di un progetto.'],
      ['Nuova visione / vista', 'Usa i pulsanti ＋ o il pulsante flottante ＋ in basso a destra.'],
      ['Colore visione', 'Tocca il pallino colorato accanto al titolo della visione.'],
      ['Rinomina visione', 'Tocca la matita ✎ accanto al titolo.'],
      ['Aprire una vista', 'Tocca la card della vista: entri subito nell’editor.'],
      ['Ricerca rapida', 'Inizia a digitare (da PC) per riempire la barra di ricerca; premi Invio per aprire la prima vista trovata.'],
      ['Scadenze', 'Le viste con righe scadute o in scadenza a breve si evidenziano con un colore di sfondo sulla card.'],
      ['Anteprima', 'Tocca il pulsante 👁 sulla card per leggere senza aprire.'],
      ['Archivio', 'Il pulsante 📦 archivia una visione: scende in fondo nel gruppo “Archivio” e smette di proporre task in Today. Resta cercabile e apribile — cercando, l’archivio si apre da solo.'],
      ['Condividere', 'Il pulsante 👥 accanto al titolo apre Team e condivisioni: da lì scegli con quale team condividere il progetto e con quale permesso — sola visibilità o modifica.'],
      ['Progetti degli altri', 'I progetti condivisi con te compaiono qui insieme ai tuoi, con una pastiglia che dice cosa puoi farci. In sola visibilità i pulsanti di modifica non ci sono e l’editor si apre in sola lettura.'],
    ],
  },
  tree: {
    titolo: 'Guida · Tree',
    icona: '🌳',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['Albero', 'Tutte le viste in gerarchia: radice in alto a sinistra, figli indentati.'],
      ['Aprire il contenuto', 'Tocca un nodo: si apre il pannello rapido con il contenuto della vista.'],
      ['Modifica veloce', 'Nel pannello puoi modificare i blocchi al volo, senza aprire l’editor completo.'],
      ['Aggiungere un ramo', 'Tocca ＋ su un nodo per creare una vista figlia.'],
      ['Spostare un ramo', 'Trascina un nodo sopra un altro per renderlo suo figlio.'],
      ['Zoom', 'Usa i pulsanti ＋ － ⌂ in alto a destra.'],
    ],
  },
  links: {
    titolo: 'Guida · Links',
    icona: '🕸️',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['Mappa', 'Ogni vista è un nodo; ogni link interno ((Nome vista)) o [[Nome vista]] scritto nel testo diventa una linea di collegamento.'],
      ['Pianeti con gravità', 'I nodi si respingono e gli archi li attirano: le viste molto collegate sono più grandi e “pesano” di più.'],
      ['Sposta i nodi', 'Trascina un nodo per riposizionarlo: il resto della mappa si riassesta da solo.'],
      ['Apri una vista', 'Doppio click (o doppio tap) su un nodo per aprirla nell’editor.'],
      ['Naviga', 'Trascina lo sfondo per spostare la mappa; rotellina per lo zoom; ⌂ Centra per reimpostare.'],
      ['Isolate', 'Il pulsante Isolate mostra o nasconde le viste che non hanno collegamenti.'],
    ],
  },
  progress: {
    titolo: 'Guida · Progress',
    icona: '📊',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['Bacheca', 'Le viste divise per fase: Idee, Progettazione, In corso, Revisione, Completato.'],
      ['Spostare una vista', 'Trascina la card nella colonna della fase desiderata.'],
      ['Evidenziazione', 'La colonna sotto il dito si illumina: al rilascio la vista finisce lì.'],
      ['Mobile', 'Trascinando verso i bordi la bacheca scorre da sola tra le sezioni.'],
      ['Cambia fase rapida', 'Tocca il pallino colorato sulla card per scegliere la fase da un elenco.'],
      ['Aprire una vista', 'Tocca il resto della card per aprirla nell’editor.'],
    ],
  },
  editor: {
    titolo: 'Guida · Editor',
    icona: '✍️',
    righe: [
      ['Ovunque', 'Ctrl+K apre la ricerca rapida da qualunque schermata: cerca fra i titoli e i contenuti di tutte le viste e fra le task di oggi, ↑↓ per scegliere, ↵ per aprire. Alt+1…5 salta alla scheda (Today · Pipe · Tree · Links · Progress). Da telefono c’è il pulsante 🔍 in alto.'],
      ['Blocchi', 'Ogni riga è un blocco markdown. Invio crea un nuovo blocco; il ＋ sulla riga ne inserisce uno subito sotto (anche in mezzo).'],
      ['Textbox', 'La casella di una riga cresce da sola col testo; trascina l’angolo in basso a destra per allargarla ancora.'],
      ['Modifica / copia / seleziona', 'Click su una riga = modifica; doppio click = copia; triplo tap = modalità selezione. Da PC: rotellina del mouse su una riga = crea una riga subito sotto.'],
      ['Ricerca', 'La barra 🔍 cerca fra le righe: le corrispondenze restano evidenziate, le altre sbiadite. Basta iniziare a digitare per riempirla in automatico.'],
      ['Elimina riga', 'Tocca l’icona 🗑 sulla riga: finisce nel Cestino, recuperabile per 7 giorni. ⌫ svuota solo il contenuto.'],
      ['Immagini', 'Il pulsante 🖼 sulla riga allega un’immagine: si vede come miniatura; toccala per aprirla a schermo intero (da lì puoi rimuoverla).'],
      ['Cestino', 'Il pulsante 🗑 Cestino mostra le righe eliminate di recente, con ripristino.'],
      ['Formattazione', 'Toolbar: Titolo, **Grassetto**, *Corsivo*, AA MAIUSCOLO, sezione —. Scorciatoie: Ctrl+B, Ctrl+I e Ctrl+M (maiuscolo) sulla selezione.'],
      ['Scadenze', 'Il pulsante 📅 imposta una scadenza: la riga prende un colore di sfondo e un countdown. Ctrl+D apre la scadenza per la riga in modifica o per quelle selezionate. Le viste con scadenze imminenti si evidenziano anche in Pipe.'],
      ['Collegamenti', 'Scrivi ((Nome vista)) o usa 🔗 per collegare (e creare) un’altra vista.'],
      ['Nidificare', 'Trascina un blocco a destra/sinistra, o usa Tab / Maiusc+Tab: le guide ad albero (│ ├ └) mostrano i livelli e restano continue tra le righe.'],
      ['Incolla strutturato', 'Incollando testo su più righe con spazi/tab, viene diviso in righe con i livelli giusti.'],
      ['Copia foglio', 'Il pulsante ⧉ Copia foglio copia tutte le righe con i rientri.'],
      ['Selezione / sezioni', '☑ Seleziona (o triplo tap, o Ctrl+S per entrare/uscire) → ☑ Tutte, ⤵ Sezione, poi ⧉ Copia · ✂ Taglia · 📌 Incolla (anche in un’altra vista). Da PC: Shift+click oppure tieni premuto su una riga per selezionare l’intera sezione (riga + rami nidificati); Canc elimina le righe, Backspace ne svuota il contenuto; clic fuori dalle righe esce dalla selezione. Scorciatoie: Ctrl+C copia, Ctrl+X taglia, Ctrl+A tutte.'],
      ['Cambia vista', 'Dentro una vista, swipe a destra/sinistra per passare alla vista precedente/successiva.'],
      ['Riordinare', 'Trascina un blocco in alto o in basso per spostarlo.'],
      ['Annulla / ripeti', 'Ctrl+Z e Ctrl+Y (o i pulsanti ↶ ↷).'],
      ['Uscire', 'Da PC premi Esc: chiude prima la modifica di una riga (salvandola) o la selezione, poi la vista.'],
      ['Focus', 'Il pulsante 🎯 nasconde la toolbar per scrivere senza distrazioni e accende il timer Pomodoro (25+5, regolabile fino a 50+10). Il timer si può tenere acceso ovunque dal menu ☰ → 🍅 Timer Pomodoro; mentre gira, il tempo restante compare anche nel titolo della scheda del browser.'],
    ],
  },
}
